@startuml
left header
<font color=000 size=18><b>Package:</b> Student

<font color=000 size=16><b>ID:</b> SC-2
<font color=000 size=16><b>Назва:</b> Перегляд власної відвідуваності.
<font color=000 size=16><b>Учасники:</b> Студент, Система.
<font color=000 size=16><b>Передумови:</b> Авторизований користувач як студент.
<font color=000 size=16><b>Результат:</b> Студент переглядає власну відвідуваність.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> ES_00: Дата проведення заняття невірна

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Студент|
start
: Студент переходить у розділ "Мої дисципліни";

|Система|
: Система надає студенту доступ до\nбази даних дисциплін, які він вивчає;
   
|Студент|
: Студент обирає потрібну йому дисципліну;   

|Система|
: Система надає доступ до відповідної дисципліни;

|Студент|
: Студент натискає кнопку "Інформація";   

|Система|
: Система надає студенту доступ до інформації з відповідної дисципліни;

|Студент|
: Студент обирає дату заняття, за яке бажає побачити відвідуваність;

|Система|
: Система надає інформацію - був студент на парі чи ні;
note right #aaffaa

<font color=red><b> Можливо ES_00.

end note

|Студент|
: Студент переглядає інформацію про відвідуваність;  
  
stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
