@startuml
left header
<font color=000 size=18><b>Package:</b> User

<font color=000 size=16><b>ID:</b> UC-3
<font color=000 size=16><b>Назва:</b> Перегляд розкладу викладача.
<font color=000 size=16><b>Учасники:</b> Неавторизований користувач, Система.
<font color=000 size=16><b>Передумови:</b> Неавторизований в системі користувач.
<font color=000 size=16><b>Результат:</b> Користувач переглядає розклад викладача.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> E_03: Введеного викладача не існує

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Неавторизований користувач|
start
: Неавторизований користувач натискає кнопку пошуку розкладу для викладачів;

|Система|
: Система надає користувачу форму, де вказане
   поле для вводу імені та фамілії викладача;

|Неавторизований користувач|
: Користувач вводить ім'я та фамілію викладача;   

: Користувач натискає кнопку "Пошук";

|Система|
: Система перевіряє наявність викладача із вказаним ім'ям;
note right #aaffaa

<font color=red><b> Можливо E_02.

end note

: Система надає розклад викладача користувачу;

|Неавторизований користувач|

: Користувач переглядає розклад;

stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
