@startuml
left header
<font color=000 size=18><b>Package:</b> User

<font color=000 size=16><b>ID:</b> UC-4
<font color=000 size=16><b>Назва:</b> Реєстрація нового облікового запису.
<font color=000 size=16><b>Учасники:</b> Неавторизований користувач, Система.
<font color=000 size=16><b>Передумови:</b> Неавторизований в системі користувач.
<font color=000 size=16><b>Результат:</b> Створений обліковий запис.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> E_04: Обліковий запис для студента уже існує
<font color=000 size=16> E_05: Введені невірні дані

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Неавторизований користувач|
start
: Неавторизований користувач натискає кнопку реєстрації нового облікового запису;

|Система|
: Система надає користувачу форму, де вказані
 поля для вводу даних студента;

|Неавторизований користувач|
: Користувач вводить дані студента
(ПІБ, факультет, група);   

: Користувач натискає кнопку "Зареєструватися";

|Система|
: Система перевіряє чи немає уже у вказаного студента
облікового запису;
note right #aaffaa

<font color=red><b> Можливо E_04.

end note
: Система перевіряє наявність студента за вказаними даними;
note right #aaffaa

<font color=red><b> Можливо E_05.

end note

: Система створює обліковий запис і зберігає його в базу даних;

|Неавторизований користувач|

: Користувач зареєстрований і може авторизуватися;

stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
