@startuml
left header
<font color=000 size=18><b>Package:</b> Teacher

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Назва:</b> Перегляд розкладу групи.
<font color=000 size=16><b>Учасники:</b> Викладач, Система.
<font color=000 size=16><b>Передумови:</b> Авторизований користувач як викладач.
<font color=000 size=16><b>Результат:</b> Користувач переглядає розклад групи.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> E_02: Введеної групи не існує

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Користувач натискає кнопку пошуку розкладу для групи;

|Система|
: Система надає користувачу форму, де вказане
   поле для вводу імені групи;

|Користувач|
: Користувач вводить ім'я групи;   

: Користувач натискає кнопку "Пошук";

|Система|
: Система перевіряє наявність групи із вказаним ім'ям;
note right #aaffaa

<font color=red><b> Можливо E_02.

end note

: Система надає розклад групи користувачу;

|Користувач|

: Користувач переглядає розклад;

stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
