@startuml
left header
<font color=000 size=18><b>Package:</b> Teacher

<font color=000 size=16><b>ID:</b> UC-3
<font color=000 size=16><b>Назва:</b> Відмічання присутності на занятті.
<font color=000 size=16><b>Учасники:</b> Викладач, Система.
<font color=000 size=16><b>Передумови:</b> Авторизований користувач як викладач.
<font color=000 size=16><b>Результат:</b> Викладач відмічає присутність певного користувача на занятті.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> E_06: Користувач не існує
<font color=000 size=16> E_07: Дата проведення занятття невірна

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Користувач переходить у розділ "Мої дисципліни";

|Система|
: Система надає користувачу доступ до бази даних дисциплін, 
  які він викладає;
   
|Користувач|
: Користувач обирає потрібну йому дисципліну;   

|Система|
: Система надає доступ до відповідної дисципліни;

|Користувач|
: Користувач нажимає кнопку "Відмітити";   

|Система|
: Система надає користувачу форму для пошуку потрібного
  користувача, якого потрібно відмітити;

|Користувач|
: Користувач вводить прізвище та ініціали шуканого користувача;

|Система|
: Система перевіряє наявність користувача за вказаними даними;

note right #aaffaa

<font color=red><b> Можливо E_06.

end note

|Користувач|
: Користувач вказує дату заняття, присутність на якому має бути
  відмічена;
  
|Система|
: Система перевіряє наявність заняття за вказаної дати;
note right #aaffaa

<font color=red><b> Можливо E_07.

end note  

|Система|  
: Система відмічає присутність шуканого користувача;

|Користувач|

: Користувач отримує повідомлення про успішне
  відмічення присутності шуканого користувача;

stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
