@startuml
left header
<font color=000 size=18><b>Package:</b> Teacher

<font color=000 size=16><b>ID:</b> TC-3
<font color=000 size=16><b>Назва:</b> Cтворення певної зустрічі, що поза розкладом.
<font color=000 size=16><b>Учасники:</b> Викладач, Система.
<font color=000 size=16><b>Передумови:</b> Авторизований користувач як викладач.
<font color=000 size=16><b>Результат:</b> Викладач створює певну зустріч, що поза розкладом.
<font color=000 size=16><b>Виключні ситуації:</b>

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Викладач|
start
: Викладач переходить у розділ "Мої дисципліни";

|Система|
: Система надає викладачу доступ до бази даних дисциплін, 
  які він викладає;
   
|Викладач|
: Викладач обирає потрібну йому дисципліну;   

|Система|
: Система надає доступ до відповідної дисципліни;

|Викладач|
: Викладач нажимає кнопку "Додати зустріч";   

|Система|
: Система надає користувачу доступ до відповідної дисципліни;


|Викладач|
: Викладач обирає дату зустрічі, яку бажає створити;

: Викладач задає інформацію, яку бажає прикріпити до зустрічі;

|Система|
: Система створює зустріч відповідної дати та прикріплює
  вказану інформацію;

|Викладач|
: Викладач отримує повідомлення про успішне створення
  зустрічі поза розкладом;  
  
stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
