@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> AC-6
<font color=000 size=16><b>Назва:</b> Додавання нового облікового запису.
<font color=000 size=16><b>Учасники:</b> Адміністратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор авторизований в системі.
<font color=000 size=16><b>Результат:</b> Адміністратор додає новий обліковий запис.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EA_01: Збій відправки
<font color=000 size=16> EA_03: Не всі необхідні поля були заповнені
<font color=000 size=16><b>Основний сценарій:</b>

end header

|Адміністратор|
start
: Адміністратор переходить на сторінку 
 за посиланням "Додати обліковий запис".;

|Система|
: Система надає необхідну сторінку.;

|Адміністратор|
: Адміністратор вводить ПІБ користувача.;

: Адміністратор обирає тип користувача
 (студент або викладач).;

: Адміністратор обирає групу(групи),
 до яких користувач буде належати.;

|Система|
: Система перевіряє поля на заповненість.;

note right #aaffaa
<font color=red><b> Можливо EA_03.
end note

: Система генерує дані для входу
 до облікового запису.;

|Адміністратор|
: Після завершення  адміністратор натискає
 кнопку "Додати" та очікує підтвердження.;

|Система|
: Система відправляє запит і підтверджує операцію
 (позначка "✓" поруч з кнопкою відправки).;

note right #aaffaa
<font color=red><b> Можливо EA_01.
end note

: Система додає нового користувача
 до бази даних.;

|Адміністратор|
stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
