@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> AC-9
<font color=000 size=16><b>Назва:</b> Додавання нової групи користувачів.
<font color=000 size=16><b>Учасники:</b> Адміністратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор авторизований в системі.
<font color=000 size=16><b>Результат:</b> Адміністратор створює нову групу та додає до неї користувачів.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EA_01: Збій відправки
<font color=000 size=16> EA_03: Не всі необхідні поля були заповнені
<font color=000 size=16><b>Основний сценарій:</b>

end header

|Адміністратор|
start
: Адміністратор переходить на сторінку 
 за посиланням "Додати групу".;

|Система|
: Система надає необхідну сторінку.;

|Адміністратор|
: Адміністратор вводить назву групи.;

|Система|
: Система перевіряє поля на заповненість.;

note right #aaffaa
<font color=red><b> Можливо EA_03.
end note

|Адміністратор|
: Адміністратор обирає облікові записи,
 що будуть входити до групи.;

: Адміністратор обирає обліковий запис користувача,
 що буде старостою групи.;

: Адміністратор обирає підгрупи,
 що будуть входити до групи.;

|Адміністратор|
: Після завершення  адміністратор натискає
 кнопку "Створити" та очікує підтвердження.;

|Система|
: Система відправляє запит і підтверджує операцію
 (позначка "✓" поруч з кнопкою відправки).;

note right #aaffaa
<font color=red><b> Можливо EA_01.
end note

: Система додає нову групу користувачів
 до бази даних.;

|Адміністратор|
stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
