@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> AC-6
<font color=000 size=16><b>Назва:</b> Видалення розкладу.
<font color=000 size=16><b>Учасники:</b> Адміністратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор авторизований в системі.
<font color=000 size=16><b>Результат:</b> Адміністратор видаляє розклад з бази даних.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EA_01: Збій відправки

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Адміністратор|
start
: Адміністратор переходить на сторінку існуючого розкладу
 за сценарієм неавторизованого користувача.;

|Система|
: Система надає необхідну сторінку.;

|Адміністратор|
: Адміністратор обирає потрібне заняття
 та натискає кнопку "❌"("Видалити").;

|Система|
: Система надає попереджувальне спливаюче вікно
 для підтвердження операції.;

|Адміністратор|
: Адміністратор підтверджує операцію
 та натискає кнопку "Так, видалити.".;

note left #aaffaa
При випадковому натисканні 
кнопки "Видалити"
адміністратор натискає кнопку 
"Відміна" і скасовує операцію.
end note

|Система|
: Система відправляє запит, підтверджує операцію
 та закриває спливаюче вікно.;

note right #aaffaa
<font color=red><b> Можливо EA_01.
end note

: Система видаляє обраний розклад з бази даних.;

|Адміністратор|
stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
