@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> AC-5
<font color=000 size=16><b>Назва:</b> Редагування існуючого розкладу занять в системі.
<font color=000 size=16><b>Учасники:</b> Адміністратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор авторизований в системі.
<font color=000 size=16><b>Результат:</b> Адміністратор вносить зміни до розкладу.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EA_01: Збій відправки
<font color=000 size=16> EA_02: Виникнення помилки за відповідним сценарієм

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Адміністратор|
start
: Адміністратор переходить на сторінку існуючого розкладу
 за сценарієм неавторизованого користувача.;

|Система|
: Система надає необхідну сторінку.;

|Адміністратор|
: Адміністратор натискає кнопку "Редагувати".;

: Адміністратор вносить зміни до розкладу
 за сценаріями.;

note left #aaffaa
AC-1 Додавання нового заняття
AC-2 Редагування доданого заняття
AC-3 Видалення доданого заняття
end note

|Система|
: Система перевіряє зміни на конфліктність
 за сценаріями.;

note right #aaffaa
<font color=red><b> Можливо EA_02.
end note

|Адміністратор|
: Адміністратор натискає кнопку "Зберегти зміни"
 та очікує підтвердження.;

|Система|
: Система відправляє запит і підтверджує операцію
 (позначка "✓" поруч з кнопкою відправки).;

note right #aaffaa
<font color=red><b> Можливо EA_01.
end note

: Система вносить зміни до обраного розкладу.;

|Адміністратор|
stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
