@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> AC-2
<font color=000 size=16><b>Назва:</b> Редагування доданого заняття в розкладі.
<font color=000 size=16><b>Учасники:</b> Адміністратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор авторизований в системі. Адміністратор редагує існуючий розклад або створює новий.
<font color=000 size=16><b>Результат:</b> Адміністратор редагує деталі заняття.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EA_00: В обраних групах вже наявне заняття в наведений проміжок часу
<font color=000 size=16> EA_01: Збій відправки

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Адміністратор|
start
: Адміністратор обирає потрібне заняття та натискає кнопку "✎"("Редагувати").;

|Система|
: Система надає необхідне спливаюче вікно.;

|Адміністратор|
: В полі "Назва" адміністратор редагує назву дисципліни
 або замінює на одну з введених раніше.;

: В полях "Початок заняття" і "Кінець заняття" адміністратор змінює
 час початку та кінця заняття.;

|Система|
: Система перевіряє новий обраний проміжок часу на наявність занять
 в цьому розкладі та інших розкладах, що закріплені за обраними групами.;

note right #aaffaa
<font color=red><b> Можливо EA_00.
end note

|Адміністратор|
: В полі "Викладач" адміністратор змінює викладача,
 що буде вести заняття.;

: В полі "Аудиторія" адміністратор змінює номер аудиторії та будівлі,
 де буде проходити заняття.;

: Адміністратор натискає кнопку "Зберегти зміни" та очікує підтвердження.;

|Система|
: Система відправляє запит, підтверджує операцію та закриває спливаюче вікно.;

note right #aaffaa
<font color=red><b> Можливо EA_01.
end note

: Система вносить зміни до обраного заняття в розкладі.;

|Адміністратор|
stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
