@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> AC-10
<font color=000 size=16><b>Назва:</b> Редагування інформації групи користувачів.
<font color=000 size=16><b>Учасники:</b> Адміністратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор авторизований в системі.
<font color=000 size=16><b>Результат:</b> Адміністратор редагує інформацію про групу.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EA_01: Збій відправки
<font color=000 size=16><b>Основний сценарій:</b>

end header

|Адміністратор|
start
: Адміністратор переходить на сторінку 
 за посиланням "Групи".;

|Система|
: Система надає необхідну сторінку.;

|Адміністратор|
: Адміністратор обирає групу.;

|Система|
: Система надає необхідну сторінку групи.;

|Адміністратор|
: Адміністратор редагує інформацію групи.;

note left #aaffaa
Редагування назви
Зміна списку членів групи
Зміна списку підгруп
end note

: Після завершення  адміністратор натискає
 кнопку "Зберегти зміни" та очікує підтвердження.;

|Система|
: Система відправляє запит і підтверджує операцію
 (позначка "✓" поруч з кнопкою відправки).;

note right #aaffaa
<font color=red><b> Можливо EA_01.
end note

: Система вносить зміни до обраної групи.;

|Адміністратор|
stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
