@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> AC-7
<font color=000 size=16><b>Назва:</b> Редагування інформації облікового запису.
<font color=000 size=16><b>Учасники:</b> Адміністратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор авторизований в системі.
<font color=000 size=16><b>Результат:</b> Адміністратор редагує інформацію облікового запису.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EA_01: Збій відправки
<font color=000 size=16><b>Основний сценарій:</b>

end header

|Адміністратор|
start
: Адміністратор переходить на сторінку 
 за посиланням "Облікові записи".;

|Система|
: Система надає необхідну сторінку.;

|Адміністратор|
: Адміністратор обирає обліковий запис.;

|Система|
: Система надає сторінку облікового запису.;

|Адміністратор|
: Адміністратор редагує інформацію облікового запису.;

note left #aaffaa
Редагування ПІБ
Зміна типу користувача
Зміна групи(груп)
end note

|Адміністратор|
: Після завершення  адміністратор натискає
 кнопку "Зберегти зміни" та очікує підтвердження.;

|Система|
: Система відправляє запит і підтверджує операцію
 (позначка "✓" поруч з кнопкою відправки).;

note right #aaffaa
<font color=red><b> Можливо EA_01.
end note

: Система вносить зміни до обраного облікового запису.;

|Адміністратор|
stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
