@startuml
left header
<font color=000 size=18><b>Package:</b> Grouphead

<font color=000 size=16><b>ID:</b> GC-2
<font color=000 size=16><b>Назва:</b> Додавання події в розклад.
<font color=000 size=16><b>Учасники:</b> Староста, Система.
<font color=000 size=16><b>Передумови:</b> Староста авторизований в системі.
<font color=000 size=16><b>Результат:</b> Староста додає подію в розклад.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EG_01: Подія перекриває існуючий розклад.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Староста|
: Староста обирає день тижня та натискає кнопку "Додати подію".;

|Система|
: Система надає необхідне спливаюче вікно.;

|Староста|
: Староста вводить назву, опис та час проведення події";

|Система|
: Система перевіряє чи не заважає ця подія існуючому розкладу.;

note right #aaffaa
<font color=red><b> Можливо EG_01.
end note

: Система додає відповідну подію до вибраного дня тижня.;

stop;

right footer

Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
