@startuml
left header
<font color=000 size=18><b>Package:</b> Grouphead

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Назва:</b> Додавання практичних завданнь або(і) лекційнійних матеріалів до занять в розкладі.
<font color=000 size=16><b>Учасники:</b> Староста, Система.
<font color=000 size=16><b>Передумови:</b> Староста авторизований в системі.
<font color=000 size=16><b>Результат:</b> Староста додає практичні завдання або(і) лекційнійних матеріалів до занять в розкладі.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EG_00: Розмір файлів перевищує ліміт

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Староста|
: Староста обирає день тижня та натискає кнопку "Додати завдання".;

|Система|
: Система надає необхідне спливаюче вікно.;

|Староста|
: Староста завантажує файли практичних завданнь або(і) лекційнійних матеріалів.;

|Система|
: Система перевіряє чи не перевещує розмір файлів ліміт.;

note right #aaffaa
<font color=red><b> Можливо EX_00.
end note

: Система додає відповіні файли до вибраного дня тижня.;

stop;

right footer

Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml