@startuml
left header
<font color=000 size=18><b>Package:</b> Grouphead

<font color=000 size=16><b>ID:</b> UC-3
<font color=000 size=16><b>Назва:</b> Заповнення списку студентів, присутніх на певному занятті.
<font color=000 size=16><b>Учасники:</b> Староста, Система.
<font color=000 size=16><b>Передумови:</b> Староста авторизований в системі.
<font color=000 size=16><b>Результат:</b> Заповнює список студентів, присутніх на певному занятті.
<font color=000 size=16><b>Виключні ситуації:</b>

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Староста|
: Староста обирає день тижня та натискає кнопку "Додати присутніх".;

|Система|
: Система надає необхідне спливаюче вікно.;

|Староста|
: Староста відмічає всіх присутніх студентів.;

|Система|
: Система заносить список присутніх студентів у базу данних.;

stop;

right footer

Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
