@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Назва:</b> Додавання нового розкладу занять до системи.
<font color=000 size=16><b>Учасники:</b> Адміністратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор авторизований в системі.
<font color=000 size=16><b>Результат:</b> Адміністратор створює розклад і закріплює його за певною групою користувачів.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: В обраних групах вже наявне заняття в наведений проміжок часу
<font color=000 size=16> EX_01: Збій відправки

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Адміністратор переходить на сторінку 
 за посиланням "Новий розклад";

|Система|
: Система надає необхідну сторінку;

|Користувач|
: В полі "Розмір" адміністратор обирає інтервал повторення розкладу.;

|Система|
: Система надає необхідну кількість полів для додавання занять;

|Користувач|
: В полі "Група" адміністратор обирає групу(групи) користувачів, 
 за якими буде закріплений новий розклад.;

|Система|
: Система заповнює поле;

|Користувач|
: Адміністратор обирає день тижня та натискає кнопку "Додати заняття";

|Система|
: Система надає необхідне спливаюче вікно;

|Користувач|
: В полі "Назва" адміністратор вводить назву дисципліни
 або обирає з введених раніше.;

: В полі "Початок заняття" і "Кінець заняття" адміністратор обирає
 час початку та кінця заняття.;

|Система|
: Система перевіряє обраний проміжок часу на наявність занять
 в цьому розкладі та розкладах, що вже закріплені за обраними групами.;

note right #aaffaa
<font color=red><b> Можливо EX_00.
end note

|Користувач|
: В полі "Викладач" адміністратор обирає викладача,
 що буде вести заняття.;

: В полі "Аудиторія" адміністратор вводить номер аудиторії та будівлі,
 де буде проходити заняття.;

: Адміністратор натискає кнопку "Додати" та очікує підтвердження;

|Система|
: Система підтверджує операцію та закриває спливаюче вікно;

: Система додає нове заняття з наведеними полями 
 до обраного дня тижня в розкладі;

|Користувач|
: Адміністратор повторює операцію додавання заняття
 поки не заповнить потрібний розклад;

: Адміністратор натискає кнопку "Створити новий розклад"
 та очікує підтвердження;

|Система|
: Система відпавляє запит і підтверджує операцію
 (позначка "✓" поруч з кнопкою відправки);

note right #aaffaa
<font color=red><b> Можливо EX_01.
end note

|Користувач|
stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
