@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC-3
<font color=000 size=16><b>Назва:</b> Видалення доданого заняття в розкладі.
<font color=000 size=16><b>Учасники:</b> Адміністратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор авторизований в системі. Адміністратор редагує існуючий розклад або створює новий.
<font color=000 size=16><b>Результат:</b> Адміністратор видаляє заняття з розкладу.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Збій відправки

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
: Адміністратор обирає потрібне заняття
 та натискає кнопку "❌"("Видалити").;

|Система|
: Система надає попереджувальне спливаюче вікно
 для підтвердження операції.;

|Користувач|
: Адміністратор підтверджує операцію
 та натискає кнопку "Так, видалити.".;

note left #aaffaa
При випадковому натисканні 
кнопки "Видалити"
адміністратор натискає кнопку 
"Відміна" і скасовує операцію.
end note

|Система|
: Система відправляє запит, підтверджує операцію
 та закриває спливаюче вікно.;

note right #aaffaa
<font color=red><b> Можливо EX_01.
end note

: Система видаляє обране заняття з розкладу.;

|Користувач|
stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
