@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC-4
<font color=000 size=16><b>Назва:</b> Додавання нового розкладу занять до системи.
<font color=000 size=16><b>Учасники:</b> Адміністратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор авторизований в системі.
<font color=000 size=16><b>Результат:</b> Адміністратор створює розклад і закріплює його за певною групою користувачів.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Виникнення помилки за відповідним сценарієм
<font color=000 size=16> EX_01: Збій відправки

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Адміністратор переходить на сторінку 
 за посиланням "Новий розклад".;

|Система|
: Система надає необхідну сторінку.;

|Користувач|
: В полі "Розмір" адміністратор обирає інтервал повторення розкладу.;

|Система|
: Система надає необхідну кількість полів для додавання занять.;

|Користувач|
: В полі "Група" адміністратор обирає групу(групи) користувачів, 
 за якими буде закріплений новий розклад.;

|Система|
: Система заповнює поле.;

|Користувач|
: Адміністратор додає нові заняття за сценарієм UC-1.;

|Система|
: Система перевіряє кожне нове додане заняття за сценарієм.;

note right #aaffaa
<font color=red><b> Можливо EX_00.
end note

|Користувач|
: Адміністратор у разі потреби редагує або видаляє додані заняття
 за сценаріями UC-2 і UC-3.;

|Система|
: Система перевіряє зміни на конфліктність за сценаріями.;

note right #aaffaa
<font color=red><b> Можливо EX_00.
end note

|Користувач|
: Після завершення складання розкладу адміністратор натискає
 кнопку "Створити новий розклад" та очікує підтвердження.;

|Система|
: Система відправляє запит і підтверджує операцію
 (позначка "✓" поруч з кнопкою відправки).;

note right #aaffaa
<font color=red><b> Можливо EX_01.
end note

|Користувач|
stop;

right footer


Система контролю навчання. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
