@startuml
entity "Користувач" {
    "ім'я"
    "прізвище"
    "пошта"
    "пароль"
    "тип користувача"
}
entity "Група" {
    "назва"
    "дисципліни"
    "учасники"
    "староста"
}
entity "Дисципліна" {
    "назва"
    "викладач"
    "слухачі (групи)"
    "дата проведення занять"
}
entity "Додаткове заняття" { 
    "назва"
    "дисципліна"
    "одноразова дата"
}
entity "Домашнє завдання" {
    "дисципліна"
    "зміст"
    "дата реченця (дедлайну)"
}
entity "Явка" {
    "користувач"
    "дисципліна"
    "дата"
}



"Користувач" --> "Дисципліна"
"Користувач" --> "Домашнє завдання"
"Користувач" --> "Явка"
"Група" --> "Користувач"
"Додаткове заняття" --> "Дисципліна"
"Дисципліна" --> "Група"
"Домашнє завдання" --> "Дисципліна"
"Явка" --> "Дисципліна"
@enduml
