@startuml
entity "Користувач" {
    "логін"
    "ім'я"
    "тип користувача"
    "група"
    "пароль"
}
entity "Група" {
    "назва"
    "староста"
}
entity "Заняття" {
    "дата"
    "час"
    "домашнє завдання"
    "назва дисципліни"
    "група"
    "викладач"
    "опис дисципліни"
}
entity "Присутність" {
    "заняття"
    "користувач"
}


"Група" "1,*"-->"1,1" "Користувач"
"Користувач" "1,1"-->"1,1" "Група"
"Заняття" "1,1"-->"0,*" "Користувач"
"Присутність" "1,1"-->"0,*" "Користувач"
"Заняття" "1,*"-->"1,*" "Група"
"Присутність" "1,1"-->"0,*" "Заняття"

@enduml
